# Generated by Django 2.2.1 on 2019-12-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_number',
        ),
        migrations.AlterField(
            model_name='document',
            name='unq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
    ]
